config/routes.rb
Rails.application.routes.draw do
  resources :chatbox
  root :to => "chatbox#index"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  post 'message', to: "messages#create"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true,length: {minimum: 10, maximum: 50}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: {case_sensitive: false},length: {maximum: 15, minimum: 3}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? , :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "you must be logged in"
      redirect_to root_path
    end
  end
end

app/controllers/chatbox_controller.rb
class ChatboxController < ApplicationController
  #before_action :require_user

  def index
    if logged_in?
      @message = Message.new
      @messages = Message.all
    else
      flash[:danger] = "You should logged in first"
      redirect_to login_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast("chatroom_channel",
                                   {msg_data: render_data(message)})
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

  def render_data(message)
    render(partial: 'message', locals: { message: message })

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, except: [:destroy]
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if( user && user.authenticate(params[:session][:password]))
      session[:user_id] = user.id
      flash[:success]= " Successfully logged in "
      redirect_to root_path
    else
      flash.now[:danger] = " You have enetred something  wrong "
      render 'new'
    end

  end

  def destroy
    session[:user_id]= nil
    flash[:success] = "Logged Out Success fully"
    redirect_to login_path
  end
  private
  def logged_in_redirect
    if logged_in?
      flash[:danger] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatbox_helper.rb
module ChatboxHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatbox/index.html.erb
<div class="container-fluid">
<%= image_tag ("img.png"), class: "rounded mx-auto d-block imgwidth rounded" %>
</div>
<br>
<div class="container">
<div class="row">
  <div class="card col-9 cardheight">
    <div class="card-body" id="msg">
      <div id="chatcontainer">

        <% @messages.each do |message| %>
          <div class="content">
            <p> <%= link_to message.user.username %>:  <%= message.body %></p>
          </div>

      <% end %>
      </div>
      <%= form_for(@message, html: {class: "content", role: "form"}, url: message_path , remote: true) do |f| %>

        <div class="input-group mb-3 jointop ">
          <%= f.text_field :body, class: "col-11 inputbottom form-control" %>
          <div class="input-group-append">
            <%= f.button "Send" , class: "btn btn-primary inputbottom btn-outline-secondary", id: "bttn1" %>
          </div>
        </div>

        <% end %>
    </div>
  </div>

  <div class="card col-3 cardheight">
  <div class="card-body ">
    <div class="content">
    <nav class ="navbar bg-light">
      <ul class ="nav navbar-nav">
          <li class ="nav-item " id="lihover" >
          <a class ="nav-link" href="#"> Home </a>
        </li>
        <li class ="nav-item" id="lihover">
          <a class ="nav-link" href="#"> Services </a>
        </li>
        <li class ="nav-item " id="lihover">
          <a class ="nav-link" href="#"> Contact </a>
        </li>
        <li class ="nav-item" id="lihover">
          <a class ="nav-link" href="#"> Blogs </a>
        </li>
      </ul>
    </nav>
    </div>
  </div>
  </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    scroll_bottom = function ()
    {
        if($('#msg').length > 0)
        {
            $('#msg').scrollTop($('#msg')[0].scrollHeight);
        }
    }

    submit_message = function ()
    {
        $('#message_body').on('keydown', function (e)
        {
            if( e.keyCode == 13)
            {
                $('button').click();
                e.target.value= " ";
            }
        })
    }

    $( document ).ready(function() {

        scroll_bottom();
        submit_message();

    });

</script>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            stoping this article to saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <%flash.each do |name,msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert"> &#215; </a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Chatbox", logged_in? ? root_path : login_path, class: " navbar-brand navlogo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item navicon">

        <% if logged_in? %>
          <%= link_to "Home", chatbox_index_path,  class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item navicon">
        <a class="nav-link" href="#">Link</a>
      </li>



    </ul>
    <ul class="navbar-nav fright  pr-5">

    <li class="nav-item dropdown fright">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Actions
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? %>
        <%= link_to "Sign out",logout_path, method: :delete, class: " dropdown-item" %>
          <% end %>
        <% if !logged_in? %>
          <%= link_to "Login ", login_path, class: " dropdown-item" %>
          <%= link_to "Sign up",  class: " dropdown-item" %>

        <% end %>
      </div>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/flash.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <%flash.each do |name,msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert"> &#215; </a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="content">
  <p> <%= link_to message.user.username %>:  <%= message.body %></p>
</div>